"""Add Chemical, Tag, and full nutrients

Revision ID: 65b0a483ed78
Revises: ac08185146ac
Create Date: 2025-07-20 22:26:00.987029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b0a483ed78'
down_revision: Union[str, Sequence[str], None] = 'ac08185146ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
