"""Update Ingredient and User models

Revision ID: 60cfb24a844c
Revises: 5ed9b29e3439
Create Date: 2025-07-20 13:34:14.900702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cfb24a844c'
down_revision: Union[str, Sequence[str], None] = '5ed9b29e3439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
