"""Update Ingredient and User models

Revision ID: ffea995ec6f0
Revises: 76c7f5a8d95a
Create Date: 2025-07-20 10:32:46.053540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffea995ec6f0'
down_revision: Union[str, Sequence[str], None] = '76c7f5a8d95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
