"""Update Ingredient and User models

Revision ID: c1e9e1b6a9f9
Revises: 08617fa59ca1
Create Date: 2025-07-20 13:17:08.620374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e9e1b6a9f9'
down_revision: Union[str, Sequence[str], None] = '08617fa59ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
