"""Update Ingredient and User models

Revision ID: 0e297569b690
Revises: 6e0fcc70b7b3
Create Date: 2025-07-19 22:45:36.399032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e297569b690'
down_revision: Union[str, Sequence[str], None] = '6e0fcc70b7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('code', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('nitrogen', sa.DECIMAL(), nullable=True))
    op.add_column('ingredients', sa.Column('phosphate', sa.DECIMAL(), nullable=True))
    op.add_column('ingredients', sa.Column('potash', sa.DECIMAL(), nullable=True))
    op.add_column('ingredients', sa.Column('sulfur', sa.DECIMAL(), nullable=True))
    op.add_column('ingredients', sa.Column('zinc', sa.DECIMAL(), nullable=True))
    op.add_column('ingredients', sa.Column('boron', sa.DECIMAL(), nullable=True))
    op.add_column('ingredients', sa.Column('density', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('cost_per_ton', sa.DECIMAL(), nullable=False))
    op.add_column('ingredients', sa.Column('source', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'email')
    op.drop_column('ingredients', 'source')
    op.drop_column('ingredients', 'cost_per_ton')
    op.drop_column('ingredients', 'density')
    op.drop_column('ingredients', 'boron')
    op.drop_column('ingredients', 'zinc')
    op.drop_column('ingredients', 'sulfur')
    op.drop_column('ingredients', 'potash')
    op.drop_column('ingredients', 'phosphate')
    op.drop_column('ingredients', 'nitrogen')
    op.drop_column('ingredients', 'code')
    # ### end Alembic commands ###
