"""Update Ingredient and User models

Revision ID: 5ed9b29e3439
Revises: c1e9e1b6a9f9
Create Date: 2025-07-20 13:24:34.026201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed9b29e3439'
down_revision: Union[str, Sequence[str], None] = 'c1e9e1b6a9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
